### ISSUE TITLE
Prioritise the features 

### ISSUE THREAD

**Issue by almahdc** [almahdc/daido-project-onboarding#4]
- [ ] Different languages

- [ ] Chatbot / contact form

- [ ] Feedback form

- [ ] OCR

- [ ] PM system (assign tasks, invite members)

- [ ] Dynamic questionnaire

- [ ] Diagrams (workflow) (https://blog.sourcerer.io/build-interactive-diagrams-with-storm-react-diagrams-f172ae26af9d; https://blog.sourcerer.io/build-interactive-diagrams-with-storm-react-diagrams-f172ae26af9d; https://modeling-languages.com/javascript-drawing-libraries-diagrams/)

- [ ] Exposed API - export info from our system to something else

- [ ] Nice overview / visualization of manufacturers and some key data

- [ ] Template for a specific type of manufacturer (cathode; know their process)

- [ ] Scanning of data

- [ ] Notification of a manufacturer accepting & finishing (or passing milestones) the onboarding

- [ ] Educational content (about the onboarding process)
